ifndef::imagesdir[:imagesdir: ../images]
:data-uri:

=== 2.2.数据库（开发环境）

本章节主要讲解Zero中数据库初始化流程，默认账号密码如：

[options="header"]
|====
|类型|账号|说明
|MySQL / TiDB|root|root账号
|MySQL / TiDB|zero|核心管理员账号
|====

==== 2.2.1.MySQL 8.0

===== 2.2.1.1.Docker-Compose

进入到zone@docker/database-dc-mysql-8目录中，该目录中包含了MySQL的Docker-Compose基础配置，为了脱敏操作，下载的版本中没有环境变量文件 *zero-mysql-8.env*，您可以直接将目录中的模板文件拷贝一份：

[source,bash]
----
$ cd zone@docker/database-dc-mysql-8
$ cp tpl.zero-mysql-8.env zero-mysql-8.env
----

使用工具或IDE编辑您的两个账号的初始密码：

[source,properties]
----
MYSQL_ROOT_PASSWORD=
MYSQL_ROOT_HOST=%
MYSQL_USER=zero
MYSQL_PASSWORD=
----

[options="header"]
|====
|参数|含义
|MYSQL_ROOT_PASSWORD|root账号密码
|MYSQL_ROOT_HOST|root账号访问的host设置，最终为 root@host中host部分
|MYSQL_USER|新建MySQL账号名
|MYSQL_PASSWORD|新建MySQL账号对应密码（初始化执行即为zero账号授权）
|====

然后执行如下命令启动MySQL：

[source,bash]
----
$ ./zero-mysql-8-@up.sh
----

运行成功后，您可以使用工具连接MySQL（确认zero/root双账号可连接）。

[source,bash]
----
$ mysql -u zero -P 3306 -h ox.engine.cn
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 11
Server version: 8.0.27 MySQL Community Server - GPL

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
----

[IMPORTANT]
====
确认您的 zero 账号执行过 init 下的初始化脚本，该脚本会为 zero 账号执行授权，您可以在MySQL中查看该账号是否授权成功。
====

===== 2.2.1.2.Terraform

==== 2.2.2.PgSQL

[TIP]
====
由于MySQL 5.x和8.x差距比较大，所以才在文件目录中带上了版本号，PgSQL则不需使用版本号标识，直接换镜像名称既可。
====

===== 2.2.2.1.Docker-Compose

进入到zone@docker/database-dc-pgsql目录中，该目录中包含了MySQL的Docker-Compose基础配置，为了脱敏操作，下载的版本中没有环境变量文件 *zero-pgsql.env*，您可以直接将目录中的模板文件拷贝一份：

[source, bath]
----
$ cd zone@docker/database-dc-pgsql
$ cp tpl.zero-pgsql.env zero-pgsql.env
----

使用工具或IDE编辑您的账号的初始密码：

[source,properties]
----
POSTGRES_PASSWORD=
POSTGRES_USER=postgres
POSTGRES_DB=postgres
TZ=Asia/Shanghai
----

[options="header"]
|====
|参数|含义
|POSTGRES_PASSWORD|postgres账号密码
|POSTGRES_USER|默认账号名
|POSTGRES_DB|默认账号访问的Schema名
|TZ|默认使用的时区
|====

然后执行如下命令启动PgSQL：

[source,bash]
----
$ ./zero-pgsql-@up.sh
----


===== 2.2.2.2.Terraform







